/** The try page's and the admin page's words, in the site's two languages. */

export type Lang = 'en' | 'zh';

export function langOf(siteLang: string): Lang {
  return siteLang.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}

/** The app's preset names and descriptions (voltip packages/shared/src/i18n). */
export const PRESET_TEXT: Record<string, Record<Lang, { name: string; description: string }>> = {
  proofread: {
    zh: { name: '校对', description: '修正错字、标点和断句，删去口头禅，其余保持原样。' },
    en: { name: 'Proofread', description: 'Fixes typos, punctuation and sentence breaks, drops filler words, keeps the rest.' },
  },
  prompt: {
    zh: { name: '提示词优化', description: '把口述的需求改写成清晰的 AI 提示词。' },
    en: { name: 'Prompt optimizer', description: 'Rewrites a spoken request as a clear prompt for an AI.' },
  },
  intent: {
    zh: { name: '意图整理', description: '采纳改口，去掉重复，把多个要点整理成列表。' },
    en: { name: 'Clarify intent', description: 'Keeps the corrected wording, removes repetition and lists multiple points.' },
  },
  chat: {
    zh: { name: '口语聊天', description: '整理成口语化的短句，句末不加句号。' },
    en: { name: 'Casual chat', description: 'Short conversational sentences without a closing full stop.' },
  },
  translate: {
    zh: { name: '中英互译', description: '修正识别错误后，在中文和英文之间互译。' },
    en: { name: 'Chinese ⇄ English', description: 'Corrects recognition errors, then translates between Chinese and English.' },
  },
  notes: {
    zh: { name: '要点纪要', description: '整理成「要点」和「待办」两组列表。' },
    en: { name: 'Key points', description: 'Organizes the text into key points and to-dos.' },
  },
  punctuation: {
    zh: { name: '只加标点', description: '只补标点和断句，不改动文字。' },
    en: { name: 'Punctuation only', description: 'Adds punctuation and sentence breaks without changing the words.' },
  },
  formal: {
    zh: { name: '书面语', description: '改写成通顺、完整的书面表达。' },
    en: { name: 'Formal', description: 'Rewrites the text as fluent, complete written language.' },
  },
};

export const LANGUAGE_NAMES: Record<string, Record<Lang, string>> = {
  auto: { zh: '自动判断', en: 'Detect' },
  zh: { zh: '中文', en: 'Chinese' },
  en: { zh: '英文', en: 'English' },
  ja: { zh: '日文', en: 'Japanese' },
  ko: { zh: '韩文', en: 'Korean' },
  yue: { zh: '粤语', en: 'Cantonese' },
};

const TEXT = {
  zh: {
    verify: '请先完成下方的人机验证，然后即可录音或上传。',
    verifyFailed: '未通过人机验证，请重试。',
    record: '开始录音',
    stop: '停止并识别',
    upload: '上传音频文件',
    uploadHint: '最长 {s} 秒，支持浏览器能播放的音频格式。',
    language: '说话的语言',
    model: '润色模型',
    preset: '润色方式',
    custom: '自定义提示词',
    customPlaceholder: '说明希望 AI 如何处理识别结果……',
    autoPolish: '识别后自动润色',
    polish: '润色',
    heard: '识别结果',
    heardPlaceholder: '录音或上传后，识别结果显示在这里；也可以直接输入文字，再点击「润色」。',
    polished: '润色结果',
    copy: '复制',
    copied: '已复制',
    recording: '录音中 {t} / {max}',
    working: '处理中……',
    timeAsr: '识别用时 {ms} 毫秒（音频 {s} 秒）',
    timePolish: '润色用时 {ms} 毫秒 · {model}',
    limits: '每个网络地址每小时最多识别 {asr} 次、润色 {polish} 次；所有访客每天合计识别 {asrDay} 次、润色 {polishDay} 次。',
    errors: {
      hourly_limit: '本小时的次数已用完，请约 {m} 分钟后再试。',
      daily_limit: '今天的体验次数已用完，请明天再试，或下载 Voltip 使用。',
      busy: '服务正忙，请稍后再试（约 {s} 秒）。',
      too_long: '音频超过 {s} 秒，请缩短后再试。',
      too_short: '录音太短，没有识别出内容。',
      not_wav: '音频格式无法处理。',
      not_audio: '无法将此文件作为音频打开。',
      mic_denied: '无法使用麦克风：请在浏览器中允许本站使用麦克风。',
      no_audio_support: '此浏览器不支持录音，请使用新版 Chrome、Edge、Firefox 或 Safari。',
      no_session: '验证已过期，请重新完成人机验证。',
      not_verified: '未通过人机验证，请重试。',
      no_text: '没有可润色的文字。',
      text_too_long: '文字太长，最多 {c} 字。',
      no_prompt: '请填写自定义提示词。',
      prompt_too_long: '提示词太长，最多 {c} 字。',
      service_failed: '服务出错，请稍后再试。',
      service_unreachable: '暂时无法连接服务，请稍后再试。',
      network: '网络错误，请检查连接后再试。',
      unknown: '发生错误：{code}',
    } as Record<string, string>,
    admin: {
      title: '管理',
      password: '管理员口令',
      signIn: '登录',
      signOut: '退出',
      refresh: '刷新',
      wrong: '口令错误。',
      signedOut: '登录已过期，请重新登录。',
      locked: '失败次数过多，已暂时锁定，请约 {m} 分钟后再试。',
      verify: '请先完成人机验证。',
      loading: '读取中……',
      generated: '统计更新于 {t}',
      edgeError: '无法读取网关统计：{e}',
      edgeStale: '暂时无法连接网关（{e}），以下是 {t} 收到的数据。',
      tryToday: '今天的在线体验：识别 {asr} / {asrDay}，润色 {polish} / {polishDay}',
      day: '日期',
      users: '用户（估算）',
      asr: '识别',
      refine: '润色',
      tryAsr: '体验·识别',
      tryRefine: '体验·润色',
      limited: '被限流',
      upstream429: 'Groq 429',
      updates: '更新检查',
      latency: '识别 / 润色耗时 p50·p95（毫秒）',
      total: '近 {n} 天合计',
      empty: '暂无统计。',
      note: '用户数按当天发出过识别、润色或体验请求的网络地址估算，共用同一网络出口的多人计为一个。「被限流」是网关因超出限制而直接拒绝的请求。',
    },
  },
  en: {
    verify: 'Complete the check below to record or upload.',
    verifyFailed: 'The check did not pass. Please try again.',
    record: 'Record',
    stop: 'Stop and recognise',
    upload: 'Upload an audio file',
    uploadHint: 'Up to {s} seconds; any format your browser can play.',
    language: 'Spoken language',
    model: 'Polish model',
    preset: 'Polish style',
    custom: 'Custom prompt',
    customPlaceholder: 'Tell the AI what to do with the recognised text…',
    autoPolish: 'Polish after recognition',
    polish: 'Polish',
    heard: 'Recognised',
    heardPlaceholder: 'The recognised text appears here after a recording or an upload; you can also type text and press Polish.',
    polished: 'Polished',
    copy: 'Copy',
    copied: 'Copied',
    recording: 'Recording {t} / {max}',
    working: 'Working…',
    timeAsr: 'Recognised in {ms} ms ({s} s of audio)',
    timePolish: 'Polished in {ms} ms · {model}',
    limits: 'Each network address can run {asr} recognitions and {polish} polishes an hour; all visitors together {asrDay} and {polishDay} a day.',
    errors: {
      hourly_limit: "This hour's tries are used up. Try again in about {m} min.",
      daily_limit: "Today's tries are used up. Come back tomorrow, or download Voltip.",
      busy: 'The service is busy. Try again in about {s} s.',
      too_long: 'The audio is longer than {s} seconds. Please shorten it.',
      too_short: 'The recording is too short to recognise.',
      not_wav: 'The audio could not be processed.',
      not_audio: 'This file cannot be opened as audio.',
      mic_denied: 'The microphone is not available: allow this site to use it in your browser.',
      no_audio_support: 'This browser cannot record. Use a recent Chrome, Edge, Firefox or Safari.',
      no_session: 'The check has expired. Please complete it again.',
      not_verified: 'The check did not pass. Please try again.',
      no_text: 'There is no text to polish.',
      text_too_long: 'The text is too long: at most {c} characters.',
      no_prompt: 'Please write a custom prompt.',
      prompt_too_long: 'The prompt is too long: at most {c} characters.',
      service_failed: 'The service failed. Please try again later.',
      service_unreachable: 'The service cannot be reached right now.',
      network: 'A network error occurred. Check your connection.',
      unknown: 'Something went wrong: {code}',
    } as Record<string, string>,
    admin: {
      title: 'Admin',
      password: 'Admin password',
      signIn: 'Sign in',
      signOut: 'Sign out',
      refresh: 'Refresh',
      wrong: 'Wrong password.',
      signedOut: 'The session has expired. Please sign in again.',
      locked: 'Too many failed attempts. Locked for about {m} min.',
      verify: 'Complete the check first.',
      loading: 'Loading…',
      generated: 'Statistics as of {t}',
      edgeError: 'The edge statistics are unavailable: {e}',
      edgeStale: 'The edge cannot be reached right now ({e}); the figures below arrived at {t}.',
      tryToday: 'Try page today: {asr} / {asrDay} recognitions, {polish} / {polishDay} polishes',
      day: 'Day',
      users: 'Users (est.)',
      asr: 'Recognition',
      refine: 'Polish',
      tryAsr: 'Try · recognition',
      tryRefine: 'Try · polish',
      limited: 'limited',
      upstream429: 'Groq 429',
      updates: 'Update checks',
      latency: 'Recognition / polish p50·p95 (ms)',
      total: 'Last {n} days',
      empty: 'No statistics yet.',
      note: 'Users are estimated from the network addresses that recognised, polished or used the try page that day; several people behind one network count as one. Limited counts the requests the edge refused for going over a limit.',
    },
  },
};

export function strings(lang: Lang) {
  return TEXT[lang];
}

/** `{name}` placeholders filled in. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
