#!/usr/bin/env python3
"""
pt-tools brand asset generator.

Emits every asset in this directory from ONE parametric definition of the mark,
so the SVGs, the wordmark and the PNG ladder can never drift apart. Re-run after
changing a parameter; do not hand-edit the generated files.

    uv run --with fonttools --with cairosvg --with pillow python3 build.py

WHY THE MARK LOOKS LIKE THIS
----------------------------
pt-tools routes PT-site RSS feeds through filter rules into downloaders and
aggregates the results back. The mark states exactly that, top to bottom:

    three feeds  ->  they converge  ->  a filter engine  ->  one dispatch

Four shapes. No metaphor that needs explaining, and nothing that reduces the
tool to "a downloader".

CONSTRUCTION RULES (all three are load-bearing)
-----------------------------------------------
1. Everything sits on a 64-unit grid inside a 1024 canvas. 1024 / 64 = 16, so at
   a 16px favicon every edge in the mark lands on a whole pixel boundary. This is
   the difference between a crisp 16px mark and grey mush: the first draft used
   112-unit strokes off-grid and the feeds rendered as ~1.2px smears.
2. Solid mass, never thin strokes. A stroke that reads at 512px disappears at 16.
3. Zero opacity anywhere. Hierarchy comes from mass, length and position only. A
   faded element degrades into a ghost at small sizes and silently changes what
   the mark means.

Construction language is inherited from the two shipped sibling icons
(AgentLens, Voxera): 1024 canvas, flat fills, hard angles, no gradients, and the
same four palette values, so the four product marks sit together.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent

# --- palette: the four locked values. Nothing else may appear in an output. ---
INK = "#0B1220"  # near-black navy — plate, wordmark slab
PAPER = "#E7EDF5"  # cool off-white — feeds and funnel (the plumbing)
BRAND = "#F97316"  # orange — the filter engine ONLY (2.7:1 on paper: never detail)
TEAL = "#14B8A6"  # teal — the dispatch

# --- geometry, expressed in 16ths so the grid contract is visible ---
U = 64  # one 16px-pixel = 64 canvas units
FEED_Y, FEED_H, FEED_W = 2, 4, 2  # three feeds, y=2..6, 2 wide
FEED_XS = (2, 7, 12)  # 3-unit gaps; ink spans 2..14, centred on 8
BAND_Y = 6  # funnel mouth — flush with the feet of the feeds
TAPER_Y = 10  # funnel throat
BLOCK_X, BLOCK_W, BLOCK_H = 6, 4, 3  # engine block, y=10..13
OUT_X, OUT_W, OUT_H = 7, 2, 2  # dispatch, y=13..15

# Feed width 2 (not 3) is load-bearing twice over: it keeps the ink box
# symmetric about the canvas centre (2..14 -> centre 8, equal 2-unit margins),
# and it keeps the gaps between feeds wider than the feeds themselves, which is
# what makes three *separate* streams read at 16px. Widening the feeds to 3 or 4
# closes the gaps into hairlines and the mark collapses into a notched slab.
GLYPH_MIN, GLYPH_MAX = FEED_XS[0] * U, (FEED_XS[2] + FEED_W) * U
GLYPH_SPAN = GLYPH_MAX - GLYPH_MIN


def mark_body(feed: str, node: str, out: str, indent: str = "  ") -> str:
    """The mark's four shapes, in draw order."""
    i = indent
    parts = [
        f'{i}<rect x="{x * U}" y="{FEED_Y * U}" width="{FEED_W * U}" height="{FEED_H * U}" fill="{feed}"/>'
        for x in FEED_XS
    ]
    parts.append(
        f'{i}<path d="M {FEED_XS[0] * U} {BAND_Y * U} '
        f"L {(FEED_XS[2] + FEED_W) * U} {BAND_Y * U} "
        f"L {(BLOCK_X + BLOCK_W) * U} {TAPER_Y * U} "
        f'L {BLOCK_X * U} {TAPER_Y * U} Z" fill="{feed}"/>'
    )
    parts.append(
        f'{i}<rect x="{BLOCK_X * U}" y="{TAPER_Y * U}" width="{BLOCK_W * U}" height="{BLOCK_H * U}" fill="{node}"/>'
    )
    parts.append(
        f'{i}<rect x="{OUT_X * U}" y="{(TAPER_Y + BLOCK_H) * U}" width="{OUT_W * U}" height="{OUT_H * U}" fill="{out}"/>'
    )
    return "\n".join(parts)


PLATE_R = 204.8  # 20% of 1024 — the same corner radius as the Voxera app icon


def write_logo() -> None:
    """Plated primary. Self-contained, so it holds on light, dark and coloured
    grounds with no media query and no <picture>. The PNG ladder comes from this.
    The glyph is NOT scaled: its bounds are already 128..960, which leaves a
    2-unit (12.5%) margin that keeps the feeds clear of the plate's corners."""
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-label="pt-tools">
  <title>pt-tools</title>
  <!-- Generated by build.py. Do not hand-edit. -->
  <rect x="0" y="0" width="1024" height="1024" rx="{PLATE_R}" ry="{PLATE_R}" fill="{INK}"/>
{mark_body(PAPER, BRAND, TEAL)}
</svg>
"""
    (HERE / "logo.svg").write_text(svg)


def write_mono() -> None:
    """Plate-less, single-colour, currentColor so an inlined copy inherits the
    host theme. The silhouette carries the whole mark here, which is the real
    test of whether the geometry works."""
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" fill="none" role="img" aria-label="pt-tools">
  <title>pt-tools</title>
  <!-- Generated by build.py. Do not hand-edit. Inherits colour from the host. -->
{mark_body("currentColor", "currentColor", "currentColor")}
</svg>
"""
    (HERE / "logo-mono.svg").write_text(svg)


# --- wordmark ---------------------------------------------------------------
# The ink slab is a decision, not laziness. Of the four locked colours only ink
# clears text contrast on paper, and ink is invisible on a dark ground. Paper
# type on an ink slab keeps the lockup inside the palette AND readable on every
# background, which is what a transplanted asset needs.
#
# Type is emitted as outlines, never <text>, so it renders identically on a
# machine with none of these fonts installed.
WORDMARK = "pt-tools"
FONT = "/usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf"

SLAB_H = 320
SLAB_R = 64  # 20% of slab height — the plate's corner ratio, held
PAD_L = 72
GLYPH_H = 184  # mark height inside the slab
GAP = 64
PAD_R = 76
TYPE_CAP = 112  # cap height: 61% of the mark


def write_wordmark() -> None:
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont

    font = TTFont(FONT)
    upem = font["head"].unitsPerEm
    cap = font["OS/2"].sCapHeight
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    glyf = font["glyf"]

    size = TYPE_CAP * upem / cap  # font size yielding exactly TYPE_CAP cap height
    scale = size / upem

    paths: list[str] = []
    x = 0.0
    y_lo = y_hi = 0.0
    for ch in WORDMARK:
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyph_set)
        glyph_set[name].draw(pen)
        d = pen.getCommands()
        if d:
            paths.append(f'<path transform="translate({x:.2f} 0)" d="{d}"/>')
            g = glyf[name]
            if g.numberOfContours:
                y_lo = min(y_lo, g.yMin)
                y_hi = max(y_hi, g.yMax)
        x += hmtx[name][0]

    text_w = x * scale
    ink_top, ink_bot = y_hi * scale, -y_lo * scale

    # Centre the type's real ink box (t-ascender to p-descender) on the slab
    # axis. Centring the baseline instead would ride visibly high.
    baseline = (SLAB_H + ink_top - ink_bot) / 2

    gs = GLYPH_H / GLYPH_SPAN
    tx = PAD_L - GLYPH_MIN * gs
    ty = (SLAB_H - GLYPH_H) / 2 - GLYPH_MIN * gs

    text_x = PAD_L + GLYPH_H + GAP
    slab_w = round(text_x + text_w + PAD_R)

    joined = "\n      ".join(paths)
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{slab_w}" height="{SLAB_H}" viewBox="0 0 {slab_w} {SLAB_H}" role="img" aria-label="pt-tools">
  <title>pt-tools</title>
  <!-- Generated by build.py. Do not hand-edit. Type is converted outlines, never a text element. -->
  <rect x="0" y="0" width="{slab_w}" height="{SLAB_H}" rx="{SLAB_R}" ry="{SLAB_R}" fill="{INK}"/>
  <g transform="translate({tx:.3f} {ty:.3f}) scale({gs:.6f})">
{mark_body(PAPER, BRAND, TEAL, indent="    ")}
  </g>
  <g fill="{PAPER}" transform="translate({text_x:.2f} {baseline:.2f}) scale({scale:.6f} -{scale:.6f})">
      {joined}
  </g>
</svg>
"""
    (HERE / "wordmark.svg").write_text(svg)
    print(f"wordmark.svg  {slab_w}x{SLAB_H}  type {size:.1f}px  cap {TYPE_CAP}")


SIZES = (512, 256, 128, 64, 32, 16)


def write_pngs() -> None:
    """Rendered natively at each size from logo.svg — never downscaled from the
    512, so each raster is a true evaluation of the vector at that pixel budget
    and the 16px file is the geometry's real verdict."""
    import cairosvg

    src = (HERE / "logo.svg").read_bytes()
    for s in SIZES:
        cairosvg.svg2png(
            bytestring=src,
            write_to=str(HERE / f"icon-{s}.png"),
            output_width=s,
            output_height=s,
            background_color=None,
        )
        print(f"icon-{s}.png")


def main() -> None:
    write_logo()
    write_mono()
    write_wordmark()
    write_pngs()
    subprocess.run(["ls", "-l", str(HERE)], check=False)


if __name__ == "__main__":
    main()
